run:
  tests: false
  timeout: 5m
linters:
  enable-all: true
  disable:
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - goerr113
    - gomnd
    - nestif
    - noctx
    - nlreturn
    - scopelint
    - wsl
    - gofumpt
    - godox