run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 20
    skip-tests: true
  funlen:
    lines: 80
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - scopelint # deprecated
    - maligned # deprecated
    - golint # deprecated
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - nlreturn
    - nilerr
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
  exclude-rules:
    - path: module/client.go
      linters:
        - noctx
    - path: internal/modules/vendor.go
      linters:
        - prealloc
