version: "2"
run:
  tests: false

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - ireturn
    - mnd
    - musttag
    - nilerr
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    gosec:
      excludes:
        - G302
        - G306
    lll:
      line-length: 160
  exclusions:
    generated: lax
    rules:
      - linters:
          - noctx
        path: module/client.go
      - linters:
          - prealloc
        path: internal/modules/vendor.go
      - path: (.+)\.go$
        text: 'ST1000: at least one file in a package should have a package comment'
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
