on:
  push:
    tags:
      - '*'

name: release

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        variant:
          - { name: wayland }
          - { name: x11     }
          - { name: full    }

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          variant: ${{ matrix.variant.name }}

      - name: Cache Go build cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.setup.outputs.gocache }}
          key: ${{ runner.os }}-${{ matrix.runs-on }}-${{ matrix.variant.name }}-gobuild-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.runs-on }}-${{ matrix.variant.name }}-gobuild-

      - name: Build
        run: go build ${TAGS:+-tags "$TAGS"} -o glass ./cmd/glass
        env:
          TAGS: ${{ steps.setup.outputs.tags }}

      - name: Package
        run: zip "glass-${GITHUB_REF_NAME}-linux-$(go env GOARCH)-${{ matrix.variant.name }}.zip" glass

      - name: Upload release artifact
        run: gh release upload "${GITHUB_REF_NAME}" "glass-${GITHUB_REF_NAME}-linux-$(go env GOARCH)-${{ matrix.variant.name }}.zip"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
